### ISSUE TITLE
1 request per 5 seconds

### ISSUE THREAD

**Issue by ivasilov** [JMPerez/promise-throttle#1]
Hey,

Thanks for making this! It really simplifies my code. I tried using it for Twitter Rate limiting, but I found the requestsPerSecond approach a bit lacking.
In the Twitter API case, a request needs to be sent every 5 seconds. I tried setting the requestsPerSecond to 0.2, but it didn't work, unfortunately.

**Comment by JMPerez** [comment]
You are right. Only integers are working at the moment.
I'm going to work on fixing it!

**Comment by JMPerez** [comment]
The initial implementation tried to resolve promises in such a way that it would eventually converge in the `requestsPerSecond` value (roughly after 1 second). However this overcomplicates the code and forces to keep track of the time when a set of promises started.

I have simplified the code to just store the time when the last promise was started. This should fix this issue.

I will merge it to master shortly, but you can see (and try out) the code using the branch [support-non-integers](https://github.com/JMPerez/promise-throttle/tree/support-non-integers).

**Comment by JMPerez** [comment]
Merged and published!

**Comment by ivasilov** [comment]
Nice!! Works perfectly.
