### ISSUE TITLE
Hey dude

### ISSUE THREAD

**Issue by thedjfresh** [JMPerez/promise-throttle#34]
Sorry for bothering you here tried to track you down elsewhere.. Im running a group of 100 labels that are creating a daily playlist together. 

Ive written a tool to help us update the app as you can imagine its a lot of work otherwise. Everythings going fine with Ajax clientside. But im having issues posting playlist with request in Node

   **var options = {
              url: 'https://api.spotify.com/v1/users/***************/playlists/***********************/tracks',
              headers: {'Authorization': 'Bearer ' + token2,Content-Type': 'application/json'
                              },
                              body:idArrayJson,      (have also tried data:)
                              json: true }
                                                    
 request.put (optionsx, function(error, response, body) {console.log (body)})**

at the moment im grabbing the token from the browser. Im getting:

**{"error":{"status":400,"message":"JSON body does not adhere to the defined endpoint parameters"}}**

and also ive had **'missing payload'**

Would really appreciate your help! your tutorials on here have been incredibly useful. I tried a bunch of node libraries and a million things before resorting to contacting you, i hope you dont mind.

Dan DJ Fresh spotify:user:iluvdrumandbass:playlist:1yRrivuEUTh5upqzeZOFBG

**Comment by JMPerez** [comment]
Hi @thedjfresh! I recommend you to reach out to @SpotifyPlatform (https://twitter.com/SpotifyPlatform) or use one of Spotify's open-source node wrappers.
I have to close this issue since it's not related with this project.
