### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by irrwitz** [JMPerez/promise-throttle#4]
Hi,

thanks for the library. It seems it is exactly what I need, however I am not sure how to use it in my case. In a promise chain, multiple POST requests are done and then the results are returned
`return Promise.all([postRequests])`. The POST requests needs to be throttled to 1 request per second, here promise-throttle is needed ;-). How can I achieve this with promise-throttle? 
I have tried this:
```javascript
var PromiseThrottle = require('promise-throttle');
  var myFunction = function(i) {
    return new Promise(function(resolve, reject) {
      setTimeout(function() {
        console.log(new Date() + ", " + i);
      }, 10);
    });
  };
  var promiseThrottle = new PromiseThrottle({
    requestsPerSecond: 1,
  });
var x = promiseThrottle.add(myFunction.bind(this, 1));
var y = promiseThrottle.add(myFunction.bind(this, 2));
var z = promiseThrottle.add(myFunction.bind(this, 3));

Promise.all([x,y,z]).then(data => console.log("Done"));
```
But 'Done' is never printed. Any idea? If the library needs to be changed and you give me some hints, I will submit a PR. Thanks a lot for your time!
Cheers,
Joshy

**Comment by JMPerez** [comment]
@irrwitz I think you are missing a call to `resolve` within your `Promise`, right after the `console.log()`.
Otherwise the promise is not marked as completed and the `Promise.all()` not fulfilled.

**Comment by irrwitz** [comment]
@JMPerez that was really the issue, thanks. This example is slightly modified from the example in the README, where the call to resolve is also missing. I made a PR https://github.com/JMPerez/promise-throttle/pull/5 with the changes in the example  maybe you find it useful.
