### ISSUE TITLE
.addAll() should return a promise

### ISSUE THREAD

**Issue by mawrkus** [JMPerez/promise-throttle#6]
Hi,
First of all, thx for the library! I'm using it for a web scraper pet project...
A small detail, for the sake of consistency/convenience, I think that .addAll() should return a promise:
```js
const oneTwoThree = promiseThrottle.addAll([
  myFunction.bind(this, 1),
  myFunction.bind(this, 2),
  myFunction.bind(this, 3)
]);

oneTwoThree.then(r => console.log("Promises " + r.join(", ") + " done"));
```

This should do the trick:
```js
PromiseThrottle.prototype.addAll = function (promises) {
  var addedPromises = promises.map(function(promise) {
    return this.add(promise);
  }.bind(this));

  return Promise.all(addedPromises);
};
```

I can submit a PR if you agree on the idea.

**Comment by JMPerez** [comment]
@mawrkus Thanks for the feedback! I think it makes completely sense. Feel free to send a PR or I can make the change myself in a few days.

**Comment by JMPerez** [comment]
Fixed through https://github.com/JMPerez/promise-throttle/pull/7
